### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by hellcry37** [fineemb/Lovelace-fan-xiaomi#1]
We would appreciate english!

**Comment by james-fry** [comment]
Yes please - english support would be great.
I started making my own "card" for xiaomi fan using picture elements card (see below) but this is much nicer!

（通过谷歌翻译）
是的，请提供英语支持。
我开始使用像素卡（见下文）为小米风扇制作自己的“卡”，但这要好得多！

![image](https://user-images.githubusercontent.com/5823294/71755369-30593400-2e82-11ea-9ced-da49169476c7.png)

**Comment by james-fry** [comment]
Just found this:

https://github.com/ikaruswill/lovelace-fan-xiaomi

**Comment by fineemb** [comment]
update v1.2
