### ISSUE TITLE
Lovelace card is incompatible with the current version of xiaomi_miio_fan.

### ISSUE THREAD

**Issue by JayZiii** [fineemb/Lovelace-fan-xiaomi#4]
Hi,

the lovelace card is incompatible with the current version of xiaomi_miio_fan.

When i try to set up 'Child Lock', 'Angle', 'Timer' and 'Natural Mode'i got this Error:

![grafik](https://user-images.githubusercontent.com/72706820/115237252-a5568880-a11c-11eb-9ec7-499d1fec5aef.png)

**Comment by syssi** [comment]
The domain as changed from `fan` to `xiaomi_miio_fan` and the service name prefix `xiaomi_miio_` was replaced by `fan_`. I will update the docs ASAP.

**Comment by syssi** [comment]
I've updated the documentation: https://github.com/syssi/xiaomi_fan/

**Comment by fineemb** [comment]
fix in v1.3.4
